
 <?php
 /**
  * Implements hook_theme_suggestions_HOOK_alter() for node.html.twig.
  */
 function kam_theme_suggestions_node_alter(array &$suggestions, array $variables) {
   // Add template suggestions based on the current view mode.
   $node = $variables['elements']['#node'];
   $suggestions[] = 'node__' . $variables['elements']['#view_mode'];
   $suggestions[] = 'node__' . $node->bundle() . '__' . $variables['elements']['#view_mode'];
 }
